flags: {}
packages:
- .
extra-deps:
- aeson-0.11.3.0
- directory-1.2.7.1
- lambdacube-compiler-0.6.0.1
- lambdacube-gl-0.5.2.4
- lambdacube-ir-0.3.0.1
- megaparsec-5.0.1
- primitive-0.6.1.0
- vector-0.11.0.0
- wavefront-0.7.1.1
resolver: lts-9.21
